import ffmpeg from 'fluent-ffmpeg';
import path from 'path';
import fs from 'fs';
import { processVideo } from '../src/services/video/processor';

const TEST_DIR = path.join(__dirname, 'test_output');

async function generateTestVideo(): Promise<string> {
  fs.mkdirSync(TEST_DIR, { recursive: true });
  const videoPath = path.join(TEST_DIR, 'input_test.mp4');

  return new Promise((resolve, reject) => {
    ffmpeg()
      .input('testsrc=duration=5:size=640x360:rate=30')
      .inputFormat('lavfi')
      .input('sine=frequency=440:duration=5')
      .inputFormat('lavfi')
      .outputOptions(['-c:v libx264', '-preset ultrafast', '-crf 28', '-c:a aac'])
      .save(videoPath)
      .on('end', () => resolve(videoPath))
      .on('error', reject);
  });
}

async function main() {
  console.log('=== Teste de integração do pipeline ===\n');

  console.log('1. Gerando vídeo de teste...');
  const inputVideo = await generateTestVideo();
  console.log(`   Vídeo criado: ${inputVideo}`);

  const outputPath = path.join(TEST_DIR, 'output_final.mp4');

  console.log('\n2. Executando pipeline completo...');
  console.log('   (narration: edge-tts grátis, caption: whisper local, face: opencv)\n');

  const start = Date.now();

  try {
    const result = await processVideo({
      inputPaths: [inputVideo],
      outputPath,
      format: 'horizontal',
      template: 'vlog',
      addCaptions: true,
      captionStyle: 'tiktok',
      backgroundMusic: 'upbeat',
      musicVolume: 0.3,
      removeSilence: true,
      autoZoom: true,
      autoColor: true,
      improveAudio: false,
      removeNoise: false,
      transitionStyle: 'fade',
      quality: 'draft',
      narration: {
        enabled: true,
        voice: 'en-US-Female',
        language: 'en',
        text: 'This is a test video generated by Vysera.',
      },
      onProgress: (p, stage) => {
        if (p % 25 === 0) console.log(`   Progresso: ${p}% (${stage})`);
      },
    });

    const elapsed = ((Date.now() - start) / 1000).toFixed(1);
    console.log(`\n3. Pipeline concluído em ${elapsed}s!`);
    console.log(`   Output: ${result.outputPath}`);
    console.log(`   Duração: ${result.duration}s`);
    console.log(`   Resolução: ${result.resolution}`);
    console.log(`   Tamanho: ${(result.fileSize / 1024 / 1024).toFixed(2)}MB`);

    if (fs.existsSync(result.outputPath)) {
      const stats = fs.statSync(result.outputPath);
      console.log(`   Arquivo existe: sim (${(stats.size / 1024).toFixed(1)}KB)`);
    }

    console.log('\n✅ Teste passou!');
  } catch (err) {
    console.error('\n❌ Teste falhou:', (err as Error).message);
    process.exit(1);
  } finally {
    fs.rmSync(TEST_DIR, { recursive: true, force: true });
  }
}

main();
